# Generated by Django 6.0.2 on 2026-05-03 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detectionhistory_uav_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroneDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('api_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning')], default='offline', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_drones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drone_devices',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DroneTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('altitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('direction', models.FloatField()),
                ('signal_strength', models.FloatField()),
                ('distance_from_base', models.FloatField()),
                ('flight_time', models.FloatField()),
                ('battery_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('vibration', models.FloatField()),
                ('gps_accuracy', models.FloatField()),
                ('prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('threat_level', models.CharField(blank=True, max_length=20, null=True)),
                ('is_threat', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='core.dronedevice')),
            ],
            options={
                'db_table': 'drone_telemetry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
