# Generated by Django 5.0.6 on 2026-03-01 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_detectionhistory_uav_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_weight', models.FloatField(default=0.6)),
                ('gnss_weight', models.FloatField(default=0.4)),
                ('suspicious_threshold', models.FloatField(default=0.3)),
                ('attack_threshold', models.FloatField(default=0.5)),
                ('high_attack_threshold', models.FloatField(default=0.7)),
                ('critical_threshold', models.FloatField(default=0.85)),
                ('auto_response_enabled', models.BooleanField(default=True)),
                ('operator_alert_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'security_config',
            },
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='combined_threat_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='fusion_threat_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='mitigation_action',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='operator_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='response_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectionhistory',
            name='response_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MitigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('threat_level', models.IntegerField()),
                ('action_taken', models.CharField(max_length=200)),
                ('success', models.BooleanField()),
                ('operator_notified', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_events', to='core.detectionhistory')),
            ],
            options={
                'db_table': 'mitigation_events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
